services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  JosefGlatz\BeuserFastswitch\:
    resource: '../Classes/*'

  JosefGlatz\BeuserFastswitch\Controller\BackendController:
    public: true

  JosefGlatz\BeuserFastswitch\Hooks\Backend\Toolbar\BackendUserPreviewToolbarItem:
    public: true
